services:
  ollama:
    image: ollama/ollama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    hostname: ollama

    volumes:
      - ./:/app
      - ./data/ollama:/root/.ollama

    ports:
      - 11434:11434

    environment:             
      - OLLAMA_NUM_GPU=1     
      - OLLAMA_GPU_LAYERS=999
      - OLLAMA_KEEP_ALIVE=-1 

  python:
    build:
      context: ./python

    hostname: python

    volumes:
      - ./:/app
      - ./data/python/home/:/home/ubuntu

    user: 1000:1000
    working_dir: /app
    command: /app/python/entrypoint.sh
