services:
  ollama:
    image: ollama/ollama

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    hostname: ollama

    volumes:
      - ./:/app
      - ./data/ollama:/root/.ollama

    ports:
      - 11434:11434

  python:
    build:
      context: .
      dockerfile: python.Dockerfile

    hostname: python

    volumes:
      - ./:/app

    user: 1000:1000
    working_dir: /app
    command: /app/python-entrypoint.sh
